name: TestDelete
on:
  push:
    branches:
    - 'test-rba-*'
jobs:
  my_first_job:
    name: My First Job on Delete
    runs-on: ubuntu-18.04
    steps:
    - name: Configure AWS Credentials
      id: aws-config
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
    - name: 'Checkout default branch (to have tf files)'
      uses: actions/checkout
    - name: Terraform init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.20
        tf_actions_subcommand: 'init'
        args: -input=false -backend-config=bucket=rba-tf-state-${{ steps.aws-config.outputs.aws-account-id }}
    - name: Print info
      env:
        S3_BUCKET: rba-tf-state-${{ steps.aws-config.outputs.aws-account-id }}
        S3_KEY: "env:/${{github.event.ref}}/disco"
      run: |
        echo I was called because ${{github.event.ref_type}} ${{github.event.ref}} was ${{github.action}}...
        echo aws s3 ls $S3_BUCKET
        aws s3 ls $S3_BUCKET
        terraform workspace list
