name: TestDelete
on:
  push:
    branches:
    - 'test-rba-*'
jobs:
  my_first_job:
    name: My First Job on Delete
    runs-on: ubuntu-18.04
    steps:
    - name: Configure AWS Credentials
      id: aws-config
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
        # aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
    # - name: Terraform init
    #   uses: hashicorp/terraform-github-action@master
    #   with:
    #     tf_actions_version: 0.12.13
    #     tf_actions_subcommand: 'init'
    - name: Print info
      run: |
        echo I was called because ${{github.event.ref_type}} ${{github.event.ref}} was deleted...
        AWS_ACCOUNT_ID=${{ steps.aws-config.outputs.aws-account-id }}
        echo aws s3 ls rba-tf-state-$AWS_ACCOUNT_ID
        aws s3 ls rba-tf-state-$AWS_ACCOUNT_ID
