name: Upload Release Asset
on:
  push:
    branches:
    - 'test-rba-*'
jobs:
  Test_Secrets:
    name: Test secrets
    runs-on: ubuntu-latest
    steps:
    - name: Display secrets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo ok
