name: Upload Release Asset
on:
  push:
    branches:
    - 'test-rba-*'
jobs:
  Test_Secrets:
    name: Test secrets
    runs-on: ubuntu-latest
    steps:
    - name: Display secrets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RBA_NAME: ${{ secrets.TEST_JSON.name }}
      run: |
        grep -i this $RBA_NAME && echo ok
